                                                                                                                                        
[project]                                                                                                                                                                                                
name = "Ercot-agent"                                                                                                                                                                                    
version = "0.0.1"                                                                                                                                                                                        
dependencies = [                                                                                                                                                                                         
    "datarobot",                                                                                                                                                                                         
    "pydantic",                                                                                                                                                                                          
    "pydantic-ai",                                                                                                                                                                                       
]                                                                                                                                                                                                        
